# CocoaPods master specs
source "https://github.com/CocoaPods/Specs.git"

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'MoyaComparison' do
  pod 'NetworkStack', :path => '../../'
  # Pods for MoyaComparison
  pod 'JSONCodable'
  pod 'SwiftyJSON'
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'SwiftyBeaver'
  pod 'Reusable'
  pod 'RealmSwift'
  pod 'SwiftyUserDefaults'
  pod 'Moya/RxSwift', '~> 8.0'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'
  pod 'Decodable'
end

target 'UnitTests' do
  # Pods for testing
end

