source "https://github.com/CocoaPods/Specs.git"

platform :ios, '8.0'
use_frameworks!

# Common Pods
#----------------------
def common_core_pods
  pod 'NetworkStack', :path => '../../'
  pod 'Decodable'
  pod 'RxSwift',
    :git => 'https://github.com/ReactiveX/RxSwift',
    :branch => '5.1.0'
end

# Target-Specific Pods
#----------------------

target 'NetworkStackDemo' do
  common_core_pods
end


target 'NetworkStackDemoTests' do
  common_core_pods
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
