source "https://github.com/CocoaPods/Specs.git"

platform :ios, '8.0'
use_frameworks!

# Common Pods
#----------------------
def common_core_pods
  pod 'NetworkStack', :path => '../../'
end

# Target-Specific Pods
#----------------------

target 'NetworkStackDemo' do
  common_core_pods
end


target 'NetworkStackDemoTests' do
  common_core_pods
  pod 'OHHTTPStubs'
  pod 'OHHTTPStubs/Swift'
end
